### ISSUE TITLE
test framework

### ISSUE THREAD

**Issue by davidmoshal** [HerringtonDarkholme/av-ts-template#2]
thanks for the template, very helpful.
would be great if you could include a testing setup :)

Thanks

David

**Comment by HerringtonDarkholme** [comment]
Hi, this template is mainly for trying out av-ts.
This is the counterpart for webpack-simple from the official repository.

I don't think I will add testing setup in this framework, before adding state management/ routing.

This repo might be a reference for using av-ts in full stack. https://github.com/whitetrefoil/vue-ts-arch
